### ISSUE TITLE
Cannot find inductors

### ISSUE THREAD

**Issue by TheBigCodeman** [lukasloetkolben/OpenpilotHardware#2]
I cannot find the inductors L3 and L4 used in the black panda, I can find ones of similar sizes but not exactly the same. Please provide links.

**Comment by niubiliter** [comment]
黄柳淞已收到您的邮件！我在伊拉克度假，稍后回复！

**Comment by lukasloetkolben** [comment]
I used these (LCSC):
L3: C149588
L4: C151872
