### ISSUE TITLE
Fertige Hardware kaufen?

### ISSUE THREAD

**Issue by HENN0** [lukasloetkolben/OpenpilotHardware#3]
Hi,
besteht die Möglichkeit eine Pandabox und eine Relais Box bei dir zu kaufen?
Ich würde Flowpilot gerne mal im MQB testen und mit VAG HW von 2024 vergleichen.

**Comment by niubiliter** [comment]
黄柳淞已收到您的邮件！我在伊拉克度假，稍后回复！

**Comment by lukasloetkolben** [comment]
Sorry für die späte Antwort. die Harnessbox wird wahrscheinlich bald zum Verkauf angeboten, aber den Panda werde ich wahrscheinlich nicht mehr produzieren.
