### ISSUE TITLE
BlackPanda firmware

### ISSUE THREAD

**Issue by alansehsu** [lukasloetkolben/OpenpilotHardware#4]
Hi,
Firstly, thank you for your contributions to the Open Source BlackPanda project. Regarding this project, I would like to ask if there are any firmware files or guides available for flashing. When I use the official firmware flashing procedure, it shows "found 0 panda(s) - []". Therefore, I hope you can provide me with some tips on what to pay attention to. Thank you.

**Comment by niubiliter** [comment]
黄柳淞已收到您的邮件！我在伊拉克度假，稍后回复！

**Comment by lukasloetkolben** [comment]
Press and hold the button while inserting the USB cable. 
Then release the button.
The STM should be in DFU mode now and you can run the flash.py script.
